version: '3.0'

services:
  mongo:
    image: mongo
    container_name: crud-mongodb
    ports:
      - "27017:27017"
    networks:
      - mongoNetwork
     
  springapi:
    image: openjdk:8-alpine
    container_name: springapi
    ports:
      - 8080:8080
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./back-end/target/crud-0.0.1-SNAPSHOT.jar:/application.jar
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/DB-CRUD
    command: ["java", "-jar", "application.jar"]
    networks:
      - mongoNetwork
      - backendNetwork
      - frontendNetwork
      
  angular:
    image: nginx:alpine
    container_name: angular
    ports: 
      - 4200:80
    depends_on:
      - springapi
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./front-end/dist/crud-app/:/usr/share/nginx/html
    networks:
      - frontendNetwork
      
networks:
  backendNetwork:
  frontendNetwork:
  mongoNetwork:
    driver: bridge